# Generated by Django 2.2.10 on 2020-04-25 16:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_auto_20200425_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ('hospital',), 'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointment'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ('hospital',), 'verbose_name': 'Doctor', 'verbose_name_plural': 'Doctors'},
        ),
        migrations.AddField(
            model_name='appointment',
            name='department',
            field=models.CharField(choices=[('1', 'Urgente'), ('2', 'Fizio-terapie'), ('3', 'Dentist'), ('4', 'Urologie'), ('5', 'Kineto-terapie'), ('6', 'Chirurgie Plastica'), ('7', 'Neurologie'), ('8', 'Cardiologie'), ('9', 'Ortopedie'), ('10', 'Ginecologie'), ('11', 'Chirurgie Generala'), ('12', 'Other..')], default='5', max_length=60),
        ),
        migrations.AddField(
            model_name='appointment',
            name='hospital',
            field=models.CharField(choices=[('1', 'Spitalul Judetean Timisoara'), ('2', 'Spitalul Militar Timisoara'), ('3', 'Spitalul Louis Turcanu Timisoara'), ('4', 'Spitalul Clinic Victor Babes '), ('6', 'Spitalul Regina Maria'), ('5', 'Other..')], default='5', max_length=50),
        ),
        migrations.AddField(
            model_name='appointment',
            name='start_day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('1', 'Urgente'), ('2', 'Fizio-terapie'), ('3', 'Dentist'), ('4', 'Urologie'), ('5', 'Kineto-terapie'), ('6', 'Chirurgie Plastica'), ('7', 'Neurologie'), ('8', 'Cardiologie'), ('9', 'Ortopedie'), ('10', 'Ginecologie'), ('11', 'Chirurgie Generala'), ('12', 'Other..')], default='5', max_length=60),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital',
            field=models.CharField(choices=[('1', 'Spitalul Judetean Timisoara'), ('2', 'Spitalul Militar Timisoara'), ('3', 'Spitalul Louis Turcanu Timisoara'), ('4', 'Spitalul Clinic Victor Babes '), ('6', 'Spitalul Regina Maria'), ('5', 'Other..')], default='5', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='content',
            field=models.CharField(default='s', max_length=250),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
